### ISSUE TITLE
restructure this repo

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/scispark_zeppelin_notebooks#12]
To address [issue #184](https://github.com/SciSpark/SciSpark/issues/184) from the SciSpark dev repo, it is suggested to:
- [ ] move workshop folders to a new folder called ESIP
- [ ] make new folder called education to move notebooks about the API to
- [ ] make folder examples to move notebooks with examples to

**Comment by rahulpalamuttam** [comment]
A small checklist item proposal:
rename the folder ESIP_Summer_2006 to ESIP_Summer_2016.

**Comment by kwhitehall** [comment]
Haha... good catch @rahulpalamuttam. Just fixed it in the PR.
